type OverviewProps = { userName: string; documentCount: number; companyCount: number; readyCompanies: number; eventCount: number; failedCompanies: number; expiringCertificates: number; lastSyncAt: string | null };

function Metric({ label, value, detail, alert = false }: { label: string; value: string; detail: string; alert?: boolean }) {
  return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_1px_2px_rgba(15,23,42,.04)]"><span className={`block size-2.5 rounded-full ${alert ? "bg-red-500" : "bg-teal-500"}`} /><p className="mt-5 text-sm font-medium text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold tracking-tight">{value}</p><p className="mt-1 text-xs text-slate-400">{detail}</p></article>;
}

function HealthRow({ label, detail, status, ok }: { label: string; detail: string; status: string; ok: boolean }) {
  return <div className="flex items-center justify-between gap-4 border-b border-slate-100 pb-4 last:border-0 last:pb-0"><div className="flex items-center gap-3"><span className={`size-2.5 rounded-full ${ok ? "bg-emerald-500" : "bg-amber-400"}`} /><div><p className="text-sm font-semibold">{label}</p><p className="text-xs text-slate-400">{detail}</p></div></div><span className={`text-xs font-bold ${ok ? "text-emerald-700" : "text-amber-700"}`}>{status}</span></div>;
}

export function OperationalOverview(props: OverviewProps) {
  const attentionCount = props.failedCompanies + props.expiringCertificates;
  const lastSync = props.lastSyncAt ? new Date(props.lastSyncAt).toLocaleString("pt-BR") : "Ainda não executada";
  return <>
    <section className="relative overflow-hidden rounded-3xl bg-[#0a4f53] p-7 text-white shadow-sm sm:p-9"><div className="absolute -right-16 -top-24 size-72 rounded-full bg-teal-300/10" /><div className="relative flex flex-wrap items-end justify-between gap-6"><div className="max-w-2xl"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-white/10 px-3 py-1 text-xs font-semibold">Ambiente fiscal interno</span><span className="rounded-full bg-emerald-300/15 px-3 py-1 text-xs font-semibold text-emerald-100">Consulta a cada 2 horas</span></div><h2 className="mt-5 text-3xl font-bold tracking-tight sm:text-4xl">Olá, {props.userName.split(" ")[0]}. Seu fiscal está sob controle.</h2><p className="mt-3 max-w-xl leading-7 text-teal-50/75">Acompanhe documentos recebidos, consultas e pontos que exigem decisão antes da integração com o ERP.</p></div><a href="#documentos" className="rounded-xl bg-white px-5 py-3 text-sm font-bold text-[#0a4f53] hover:bg-teal-50">Abrir caixa fiscal</a></div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Documentos" value={props.documentCount.toLocaleString("pt-BR")} detail={`${props.eventCount} evento(s) fiscal(is)`} /><Metric label="Empresas ativas" value={`${props.readyCompanies}/${props.companyCount}`} detail="Certificado A1 vinculado" /><Metric label="Exige atenção" value={String(attentionCount)} detail="Falhas ou certificados próximos do vencimento" alert={attentionCount > 0} /><Metric label="Última consulta" value={props.lastSyncAt ? new Date(props.lastSyncAt).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" }) : "—"} detail={lastSync} /></section>
    <section id="integracao" className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><article className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-teal-700">Central operacional</p><h3 className="mt-1 text-xl font-bold">O que exige atenção</h3></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${attentionCount ? "bg-red-50 text-red-700" : "bg-emerald-50 text-emerald-700"}`}>{attentionCount ? `${attentionCount} pendência(s)` : "Tudo em ordem"}</span></div><div className="mt-6 space-y-3">{props.failedCompanies ? <div className="rounded-xl border border-red-100 bg-red-50 p-4"><p className="font-semibold text-red-900">Sincronização com falha</p><p className="mt-1 text-sm text-red-700">{props.failedCompanies} empresa(s) precisam de análise.</p></div> : null}{props.expiringCertificates ? <div className="rounded-xl border border-amber-100 bg-amber-50 p-4"><p className="font-semibold text-amber-900">Certificado próximo do vencimento</p><p className="mt-1 text-sm text-amber-700">{props.expiringCertificates} certificado(s) vencem nos próximos 30 dias.</p></div> : null}{!attentionCount ? <div className="rounded-xl border border-emerald-100 bg-emerald-50 p-4"><p className="font-semibold text-emerald-900">Nenhuma pendência técnica detectada</p><p className="mt-1 text-sm text-emerald-700">Consultas e certificados não apresentam alertas imediatos.</p></div> : null}</div></article><article className="rounded-2xl border border-slate-200 bg-white p-6"><p className="text-xs font-bold uppercase tracking-widest text-slate-500">Saúde das integrações</p><h3 className="mt-1 text-xl font-bold">Conectores fiscais</h3><div className="mt-6 space-y-4"><HealthRow label="NFS-e · ADN Nacional" detail="Captura e eventos" status={props.readyCompanies ? "Operacional" : "Aguardando A1"} ok={props.readyCompanies > 0} /><HealthRow label="Agendamento automático" detail="Ciclo de duas horas" status="Ativo" ok /><HealthRow label="NF-e · SEFAZ Nacional" detail="NFeDistribuicaoDFe" status="Próxima sprint" ok={false} /></div></article></section>
  </>;
}
